@host=https://localhost:7094

### Register
POST {{host}}/authentication/register
Content-Type: application/json
{
  "firstName": "Murat",
  "lastName": "Yilmaz",
  "email": "test@live.nl",
  "password": "pass123"
}

### Login
POST {{host}}/authentication/login
Content-Type: application/json
{
  "email": "test@live.nl",
  "password": "pass123"
}

### Dinners
GET {{host}}/burgers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMWI2OGQ3OS0wYWMwLTQ2NjgtOTMyNC0zOGExOTNhNTg5NTkiLCJnaXZlbl9uYW1lIjoiTXVyYXQiLCJmYW1pbHlfbmFtZSI6IllpbG1heiIsImp0aSI6IjQwMjY4NGQ0LTVhZDYtNDQ5OS1hMDFkLWUxODkwZGEyZTZkYiIsImV4cCI6MTc2NjUyNDA1NCwiaXNzIjoiTXlUZXN0IiwiYXVkIjoiTXlUZXN0In0.buNs3aV1lM-DFdT3dNDUal5mfuLRIq_4IqnlLorFPyg

### BurgerRegister
POST {{host}}/burgers/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMWI2OGQ3OS0wYWMwLTQ2NjgtOTMyNC0zOGExOTNhNTg5NTkiLCJnaXZlbl9uYW1lIjoiTXVyYXQiLCJmYW1pbHlfbmFtZSI6IllpbG1heiIsImp0aSI6IjQwMjY4NGQ0LTVhZDYtNDQ5OS1hMDFkLWUxODkwZGEyZTZkYiIsImV4cCI6MTc2NjUyNDA1NCwiaXNzIjoiTXlUZXN0IiwiYXVkIjoiTXlUZXN0In0.buNs3aV1lM-DFdT3dNDUal5mfuLRIq_4IqnlLorFPyg
Content-Type: application/json
{
  "Name": "Burgabc12",
  "Description": "Nice burgerr"
}