@host=https://localhost:7276
@apiKey=key-1-super-secret
@myBearerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMDNkZmVmMC03YTViLTRkMzQtOWMyYS00ZjY5ZThmNGM1NzgiLCJnaXZlbl9uYW1lIjoiVm9vcm5hYW0iLCJmYW1pbHlfbmFtZSI6IkFjaHRlcm5hYW0iLCJqdGkiOiI1N2ViMjljNC1jOWJmLTQ2OTUtYTFlNC03ZDJlZjBjNTk2ZmEiLCJleHAiOjE3NzA1NzA1OTEsImlzcyI6Ik15LUFwaSIsImF1ZCI6Ik15LUFwaSJ9.MwmpRpNNDuJJ4djctARhB47JDYDnNTlw37mP-GNduQI

# Note: In JSON the convention is to use PasCal

### Register
POST {{host}}/api/v1/authentication/create
X-Api-Key: {{apiKey}}
Content-Type: application/json
{
  "FirstName": "Voornaam",
  "LastName": "Achternaam",
  "Email": "test@teamdevs.nl",
  "Password": "pass123"
}

### Login
POST {{host}}/api/v1/authentication/login
X-Api-Key: {{apiKey}}
Content-Type: application/json
{
  "Email": "test@teamdevs.nl",
  "Password": "pass123"
}

### Get artist
GET {{host}}/api/v1/artists?name=311
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}

### Update artist
PUT {{host}}/api/v1/artists/5
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}
Content-Type: application/json
{
  "Name": "3111"
}

### Import Artists
PUT {{host}}/api/v1/artists/import
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}

### Create Artists
POST {{host}}/api/v1/artists
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}
Content-Type: application/json
[
  {
    "Name": "MyNewArtisttttt"
  }
]

### Delete Artist
DELETE {{host}}/api/v1/artists/2
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}
Content-Type: application/json

### Create Song
POST {{host}}/api/v1/songs
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}
Content-Type: application/json
{
  "Name": "newsongggggggg",
  "Year": 1800,
  "ArtistName": "311",
  "Shortname": "newartistName",
  "Bpm": 10,
  "Duration": 50000,
  "Genre": "Metal",
  "SpotifyId": "newartistName",
  "Album": "newartistName"
}

### Delete Song
DELETE {{host}}/api/v1/songs/1
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}


### Get Songs
GET {{host}}/api/v1/songs?Genre=Metal
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}