@host=https://localhost:7276
@apiKey=key-1-super-secret
@myBearerToken=

# Note: In JSON the convention is to use PasCal

### Register
POST {{host}}/api/authentication/create
X-Api-Key: {{apiKey}}
Content-Type: application/json
{
  "FirstName": "Voornaam",
  "LastName": "Achternaam",
  "Email": "test@teamrockstars.nl",
  "Password": "pass123"
}

### Login
POST {{host}}/api/authentication/login
X-Api-Key: {{apiKey}}
Content-Type: application/json
{
  "Email": "test@teamrockstars.nl",
  "Password": "pass123"
}

### Get artist
GET {{host}}/api/artists?name=3111
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}

### Update artist
PUT {{host}}/api/artists/5
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}
Content-Type: application/json
{
  "Name": "3111"
}

### Import Artists
PUT {{host}}/api/artists/import
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}

### Create Artists
POST {{host}}/api/artists
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}
Content-Type: application/json
[
  {
    "Name": "MyNewArtisttttt"
  }
]

### Delete Artist
DELETE {{host}}/api/artists/2
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}
Content-Type: application/json

### Create Song
POST {{host}}/api/songs
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}
Content-Type: application/json
{
  "Name": "newsongg",
  "Year": 1800,
  "ArtistName": "311",
  "Shortname": "newartistName",
  "Bpm": 10,
  "Duration": 50000,
  "Genre": "newartistName",
  "SpotifyId": "newartistName",
  "Album": "newartistName"
}

### Delete Song
DELETE {{host}}/api/songs/1
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}


### Get Songs
GET {{host}}/api/songs?Genre=Metal
X-Api-Key: {{apiKey}}
Authorization: Bearer {{myBearerToken}}